#import "../../utils.typ": *

== VRCX Insights <ngd:vi>

#columns(2)[
  #figure-image(path: "../../resources/vrcx.png")[Preview of the image generated by the program]

  #colbreak()

  === Key Points
  - Implemented a simple (but surprisingly effective) data mining algorithm based on thresholds
  - Uses an external data source (not controlled by me)

  === Technologies Used
  - Rust
  - Tokio (Async Framework)
  - SQLite

  === Links
  - #github-link(repo: "vrcx-insights")
]
